#!/bin/bash
#
# Zabbix agent extension for monitoring CATIA license usage

. /etc/zabbix/zabbix-catialic.conf
AWKSCRIPT=/etc/zabbix/zabbix-catialic.awk
BUFFER=/tmp/zabbix-catialic
SOFTWARE="curl sed jo"

function discover_catialic() {
   jo -p data=$( jo -a $(
      ls $BUFFER | while read feature
      do
         jo {\#FEATURE}=\"$feature\"
      done
      ))
}

function getdata() {
   mkdir $BUFFER.$$; chmod 0750 $BUFFER.$$
   cd $BUFFER.$$

   curl -sS -q $LICENSE_URL | awk -f $AWKSCRIPT

   test -d $BUFFER && mv $BUFFER $BUFFER.old
   mv $BUFFER.$$ $BUFFER
   rm -rf $BUFFER.old
}

function sanity_check() {
   ok=1
   for prog in $SOFTWARE
   do
      which $prog > /dev/null || { echo "Missing program $prog."; ok=0; }
   done
   test -f $CFG || { echo "Missing configfile $CFG"; ok=0; }
   test $ok -ne 1 && { echo "Sanity check failed. Aboring." ; exit 1; }
}

sanity_check

action=$1
feature=$2

case "$action" in
getdata)
	getdata
;;
catialic.discover)
	discover_catialic
;;
catialic.master)
   test -f $BUFFER/$feature && grep -w $feature $BUFFER/$feature
;;
esac
