#!/bin/bash
#
# Zabbix agent extension for monitoring LDAP

. /etc/zabbix/zabbix-ldap.conf
BUFFER=/tmp/zabbix-ldap
SOFTWARE="jo ldapwhoami awk"

function discover_ldap() {
   jo -p data=$(jo -a $(
   for host in $LDAP_HOSTS
   do
     jo {\#LDAPHOST}=$host
   done ) )
}

function getdata() {
   mkdir $BUFFER.$$; chmod 0750 $BUFFER.$$
   chown zabbix:zabbix $BUFFER.$$
   cd $BUFFER.$$

   for host in $LDAP_HOSTS
   do
     (time ldapwhoami -H ldap://$host -ZZ -D $BIND_DN -w $BIND_PW -v ) 2>&1 | awk -e '{ if ($1 == "Result:") {gsub(/[()]/, "", $3); printf("result:%s\n", $3) }; if ($1 == "ldap_start_tls:") { gsub(/[()]/, "", $6); printf("result:%s\n", $6) }; if ($1 == "ldap_bind:")  {gsub(/[()]/, "", $4); printf("result:%s\n", $4) }; if ($1 == "real") { gsub(/0m/, "", $2); gsub(/s$/, "", $2); printf("time:%s", $2) } }' > $host
   done

   test -d $BUFFER && mv $BUFFER $BUFFER.old
   mv $BUFFER.$$ $BUFFER
   rm -rf $BUFFER.old
}

function sanity_check() {
   ok=1
   for prog in $SOFTWARE
   do
      which $prog > /dev/null || { echo "Missing program $prog."; ok=0; }
   done
   test -f $CFG || { echo "Missing configfile $CFG"; ok=0; }
   test $ok -ne 1 && { echo "Sanity check failed. Aboring." ; exit 1; }
}

sanity_check

action=$1
host=$2

case "$action" in
  getdata)
    getdata
    ;;
  ldap.discover)
    discover_ldap
    ;;
  ldap.master)
    test -f $BUFFER/$host && cat $BUFFER/$host
    ;;
esac
