#!/bin/bash
#
# Zabbix agent extension for monitoring devices in /proc/diskstats

BUFFER=/tmp/zabbix-diskstats
SOFTWARE="jo"

function discover_disks() {
   jo -p data=$( jo -a $(
   lsblk -ro NAME,TYPE 2>/dev/null | egrep 'disk|raid?' | sort -u | while read disk rest
   do
      jo {\#DISK}=${disk}
   done ) )
}

function getdata() {
   mkdir $BUFFER.$$; chmod 750 $BUFFER.$$
   cd $BUFFER.$$

   lsblk -ro NAME,TYPE 2>/dev/null | egrep 'disk|raid?' | sort -u | while read disk rest
   do
      grep -w $disk /proc/diskstats | while read MAJOR MINOR DMNAME READS_COMPLETED READS_MERGED READS_SECTORS READS_TIME WRITES_COMPLETED WRITES_MERGED WRITES_SECTORS WRITES_TIME IO_QUEUE IO_TIME WIO_TIME
      do
         cat <<-EOF > $disk
				MAJOR:$MAJOR
				MINOR:$MINOR
				DMNAME:$DMNAME
				READS_COMPLETED:$READS_COMPLETED
				READS_MERGED:$READS_MERGED
				READS_SECTORS:$READS_SECTORS
				READS_TIME:$READS_TIME
				WRITES_COMPLETED:$WRITES_COMPLETED
				WRITES_MERGED:$WRITES_MERGED
				WRITES_SECTORS:$WRITES_SECTORS
				WRITES_TIME:$WRITES_TIME
				IO_QUEUE:$IO_QUEUE
				IO_TIME:$IO_TIME
				WIO_TIME:$WIO_TIME
			EOF
      done
   done

   test -d $BUFFER && mv $BUFFER $BUFFER.old
   mv $BUFFER.$$ $BUFFER
   rm -rf $BUFFER.old
}

function sanity_check() {
   ok=1
   for prog in $SOFTWARE
   do
      which $prog > /dev/null || { echo "Missing program $prog."; ok=0; }
   done
   test -f $CONFIG || { echo "Missing configfile $CONFIG"; ok=0; }
   test $ok -ne 1 && { echo "Sanity check failed. Aboring." ; exit 1; }
}

sanity_check

action=$1
arg=$2

case "$action" in
    getdata)
        getdata
        ;;
    diskstats.discover)
        discover_disks
        ;;
    diskstats.master)
        test -f $BUFFER/$arg && cat $BUFFER/$arg
        ;;
esac
